name: flutter_open_xr_example
description: Minimal Flutter counter sample for flutter_open_xr.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_open_xr:
    path: ..

flutter:
  uses-material-design: true
