name: flutter_open_xr
description: CLI package to build Flutter projects into a Windows OpenXR runtime host.
version: 0.1.0
# publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.5.0
  path: ^1.9.0

executables:
  flutter_open_xr:
